version: '3.9'

services:
  summarizer:
    build: .
    working_dir: /app
    command: python agent_cli.py
    volumes:
      - /Users/marcelsalej/hackweek2025/standup-summarizer:/app:rw
    networks:
      - standup-summarizer_default
    stdin_open: true
    tty: true

networks:
  standup-summarizer_default:
    external: true