version: '3.9'

services:
  summarizer:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
        -  /Users/marcelsalej/hackweek2025/standup-summarizer:/app 
    env_file:
      - .env
    stdin_open: true
    tty: true
    command: python agent_cli.py