# standup-summarizer/docker-compose.yml
version: "3.8"
services:
  summarizer:
    build: .
    env_file:
      - .env
    volumes:
      - .:/app # This syncs your current folder with the /app folder inside the container
    # IMPORTANT: Add these two lines for interactive input
    stdin_open: true
    tty: true